---


- name: Copy daytrader3.py.j2 template
  ansible.builtin.template:
   src: "../twas_cell_common_daytrader/templates/daytrader3.py.j2"
   dest: "daytrader3.py"

- name: Copy daytrader_config.py.j2 template
  ansible.builtin.template:
   src: "../twas_cell_common_daytrader/templates/daytrader_config.py.j2"
   dest: "daytrader_config.py"

- name: Copy daytrader_vars.py.j2 template
  ansible.builtin.template:
   src: "../twas_cell_common_daytrader/templates/daytrader_vars.py.j2"
   dest: "daytrader_vars.py"

- name: Copy resource_scripts.py.j2 template
  ansible.builtin.template:
   src: "../twas_cell_common_daytrader/templates/resource_scripts.py.j2"
   dest: "resource_scripts.py"

- name: Copy daytrader app
  ansible.builtin.copy:
   src: "{{ DefaultEarFile }}"
   dest: "~/{{ DefaultEarFile }}"

- name: Run the daytrader config jython script
  ansible.builtin.shell: "{{ install_base }}/{{ twas_dir }}/profiles/{{ profile_name }}/bin/wsadmin{{ ext }} -lang jython -username {{ twas_username }} -password {{ twas_password }} -f daytrader_config.py"
  register: daytraderConfigOutput
  failed_when: ( daytraderConfigOutput.rc not in [ 0, 255 ] )

- name: DaytraderConfigOutput
  ansible.builtin.debug:
    msg: "{{ daytraderConfigOutput.stdout_lines }}"

- name: Run the daytrader3 application install jython script
  ansible.builtin.shell: "{{ install_base }}/{{ twas_dir }}/profiles/{{ profile_name }}/bin/wsadmin{{ ext }} -lang jython -username {{ twas_username }} -password {{ twas_password }} -f daytrader3.py"
  register: daytrader3Output
  failed_when: ( daytrader3Output.rc not in [ 0, 255 ] )

- name: Daytrader3Output
  ansible.builtin.debug:
    msg: "{{ daytrader3Output.stdout_lines }}"