---
- name: check on-prem db2 for db2jcc jars
  stat:
   path: "sqllib/java/db2jcc4.jar"
  register: onprem

- block:
  - name: fetch db2jcc4.jar
    fetch:
      src: ~/sqllib/java/db2jcc4.jar
      dest: /tmp/db2jcc4.jar
      flat: yes
  when: onprem.stat.exists == True

- name: check container db2 for db2jcc jars
  stat:
   path: "~/{{ svt_db_dir }}/backup/db2jcc4.jar"
  register: container

- block:
  - name: fetch db2jcc4.jar
    fetch:
      src: ~/{{ svt_db_dir }}/backup/db2jcc4.jar
      dest: /tmp/db2jcc4.jar
      flat: yes
  when: container.stat.exists == True
