---
- name: Unix kill a process
  when: ansible_system is not search('CYG')
  block:
    # logic below to force kill linux  process
    - name: Get running processes list from remote host
      ignore_errors: true
      ansible.builtin.shell: "ps -few | grep {{ linux_process_to_kill }} | awk '{print $2}'"
      register: running_processes

    - name: Kill running processes
      ignore_errors: true
      ansible.builtin.shell: "kill {{ item }}"
      with_items: "{{ running_processes.stdout_lines }}"

    - name: Kill wait_for
      ansible.builtin.wait_for:
        path: "/proc/{{ item }}/status"
        state: absent
        timeout: 60
      with_items: "{{ running_processes.stdout_lines }}"
      ignore_errors: true
      register: WsServer_processes

    - name: Force kill stuck processes
      ignore_errors: true
      ansible.builtin.shell: "kill -9 {{ item }}"
      with_items: "{{ WsServer_processes.results | select('failed') | map(attribute='item') | list }}"

- name: Windoze reboot system
  when: ansible_system is search('CYG')
  block:
    - name: Reboot Windows manually
      ansible.builtin.shell: shutdown /r /t 0
      async: 0
      poll: 0
      ignore_errors: true

    - name: Wait for system to come back online
      ansible.builtin.wait_for_connection:
        timeout: 600
        delay: 30
