---

- name: Check if previous liberty installed
  ansible.builtin.stat:
    path: "{{ install_base }}/wlp/bin/server"
  register: islib

- name: Perform liberty operations
  when: islib.stat.exists
  block:
    - name: Check liberty install type
      ansible.builtin.shell: "{{ install_base }}/wlp/bin/productInfo version --verbose"
      register: productOutput

    - name: Upgrade liberty version
      tags: upgrade
      when: "'InstallationManager' in productOutput.stdout"
      block:
      - name: Check if imcl installed as a prereq
        ansible.builtin.stat:
          path: "{{ install_base }}/IM/eclipse/tools/imcl"
        register: isimcl
        failed_when: isimcl.stat.exists == False

      - name: If using remote jdk repo
        when: jdk_repo.type == 'remote'
        block:
          - name: Generate external ibm secureStorageFile.store
            ansible.builtin.shell: "{{ cygwin }}{{ install_base }}/IM/eclipse/tools/imutilsc saveCredential -url  \
              {{ jdk_repo.url.default }}/{{ im_liberty_jdk_package }}{{ im_java_short_version }}  \
              -userName {{ external_ibmuser }} -userPassword '{{ external_ibmpass }}' \
              -secureStorageFile {{ cygwin }}{{ install_base }}/IM/secureStorageFile.store"
            register: saveCredentialOutput
            retries: 3
            delay: 10
            until: saveCredentialOutput.rc == 0

          - name: SaveCredentialOutput
            ansible.builtin.debug:
              msg: "{{ saveCredentialOutput.stdout_lines }}"

      - name: Set the mirror jdk repo url
        when: jdk_repo.type == 'mirror'
        # Internal IBM networking hack
        block:
          - name: Adjust the jdk_repo_url to use the internal IBM mirror
            block:
              - name: Test connectivity to hostname-based mirror URL ip
                ansible.builtin.uri:
                  url: "{{ jdk_repo.url.internal_ip }}"
                  method: HEAD
                  timeout: 5
                  validate_certs: false
                register: hostname_url_test
                failed_when: false

              - name: Set jdk_repo_url based on connectivity test ip
                when: hostname_url_test is succeeded
                ansible.builtin.set_fact:
                  jdk_repo_url: "{{ jdk_repo.url.internal_ip }}"

              - name: Test IP connnectivity to hostname-based mirror URL ip
                when: jdk_repo_url is not defined
                block:
                  - name: Test connectivity to hostname-based mirror URL dns
                    ansible.builtin.uri:
                      url: "{{ jdk_repo.url.internal_dns }}"
                      method: HEAD
                      timeout: 5
                      validate_certs: false
                    register: hostname_url_test
                    failed_when: false

                  - name: Set jdk_repo_url based on connectivity test dns
                    when: hostname_url_test is succeeded
                    ansible.builtin.set_fact:
                      jdk_repo_url: "{{ jdk_repo.url.internal_dns }}"

      # - name: List available jdks in the target repository
      #   ansible.builtin.shell: "{{ install_base }}/IM/eclipse/tools/imcl listAvailablePackages \
      #     -repositories https://www.ibm.com/software/repositorymanager/{{ im_liberty_jdk_package }}{{ im_java_short_version }} \
      #     -secureStorageFile {{ cygwin }}{{ install_base }}/IM/secureStorageFile.store"
      #   register: jdkDebugOutput

      # - name: List available jdks in the target repository output ( possibly missing versions causing errors )
      #   ansible.builtin.debug:
      #     msg: "{{ jdkDebugOutput.stdout_lines }}"

      - name: Upgrade liberty jdk repo
        ansible.builtin.debug:
          msg: "{{ jdk_repo_url }}/{{ im_liberty_jdk_package }}{{ im_java_short_version }}/repository.config"

      - name: Upgrade liberty jdk
        ansible.builtin.shell: "{{ install_base }}/IM/eclipse/tools/imcl install {{ im_liberty_jdk_package }}{{ im_java_short_version }} \
          -repositories {{ jdk_repo_url }}/{{ im_liberty_jdk_package }}{{ im_java_short_version }}/repository.config \
          -installationDirectory {{ cygwin }}{{ install_base }}/{{ liberty_dir }} \
          -acceptLicense -secureStorageFile {{ cygwin }}{{ install_base }}/IM/secureStorageFile.store \
          -preferences com.ibm.cic.common.core.preferences.eclipseCache={{ cygwin }}{{ install_base }}/{{ shared_dir }}"
        register: UpgradeOutput

      - name: UpgradeOutput
        ansible.builtin.debug:
          msg: "{{ UpgradeOutput.stdout_lines }}"

      - name: Check if usr/servers has server.env
        ansible.builtin.stat:
          path: "{{ wlp_usr_dir }}/servers/{{ wl_server }}/server.env"
        register: isserverenv

      - name: Remove JAVA_HOME from any servers server.env
        when: isserverenv.stat.exists
        ansible.builtin.lineinfile:
          path: "{{ wlp_usr_dir }}/servers/{{ wl_server }}/server.env"
          regexp: "^JAVA_HOME*"
          state: absent

      - name: Check if wlp/etc/server.env the global JAVA_HOME in server.env
        ansible.builtin.stat:
          path: "{{ install_base }}/{{ liberty_dir }}/etc/server.env"
        register: isserverenv

      - name: Adust the  global JAVA_HOME in server.env
        when: isserverenv.stat.exists
        ansible.builtin.lineinfile:
          path: "{{ install_base }}/{{ liberty_dir }}/etc/server.env"
          regexp: "^JAVA_HOME*"
          line: 'JAVA_HOME={{ install_base }}/{{ liberty_dir }}/java/{{ im_java_short_version }}.0'
          state: present

      - name: ListInstalledPackages
        ansible.builtin.shell: "{{ install_base }}/IM/eclipse/tools/imcl listInstalledPackages -long"
        register: packageOutput

      - name: PackageOutput
        ansible.builtin.debug:
          msg: "{{ packageOutput.stdout_lines }}"

      - name: Print the Liberty version
        ansible.builtin.shell: "{{ install_base }}/{{ liberty_dir }}/bin/server version"
        register: versionOutput

      - name: PackageOutput
        ansible.builtin.debug:
          msg: "{{ versionOutput.stdout_lines }}"
