---
- name: Upgrade WebSphere tWAS MoRE
  tags: upgrade
  block:
  - name: Copy im_was_upgrade.xml template
    ansible.builtin.template:
      src: "im_upgrade_twas_more_{{ twas_release }}.xml.j2"
      dest: "im_was_upgrade.xml"
      mode: '0644'

  - name: Upgrade tWAS MoRE product
    ansible.builtin.include_role:
      name: im_upgrade_was_product
    vars:
      was_product_dir: "{{ install_base }}/{{ twas_dir }}"
