---
# can override with local mirror
jdk_repo:
  type: 'remote'  # Options: 'mirror' (local mirror) or 'remote' (direct IBM repository)
  url:
    external: 'https://www.ibm.com/software/repositorymanager/'
    internal: 'https://yourdns/binaries/semeru_mirrored_repo'
